using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Pathmaker : MonoBehaviour {

	private int counter = 0; //counter var will track # of tiles instantiated
	public Transform floorPrefab; //assign Tile to this in inspector
	public Transform pathmakerSpherePrefab; //assign in in inspector
	public static int globalTileCount; //prevents building over 500 tiles
	public int maxTiles; //maximum number of tiles to be generated by all pathmakers
	int pathmakerLife; //variable used to randomize counter bound

	void Start () {
		pathmakerLife = Random.Range (25, 76); //life of pathmaker is random number between 25 and 75
		maxTiles = Random.Range (150, 501); //max number of tiles to be created between 150 and 500
	}
	
	// Update is called once per frame
	void Update () {
		if (counter < pathmakerLife) {

			//generates random number between 0 and 1
			float rand = Random.Range (0.0f, 1.0f);

			if (rand < 0.15f) {

				//rotates 90 degrees if random number is less than 0.25
				transform.Rotate (0f, 90f, 0f);
				
			} else if (rand < 0.30f) {

				//rotates -90 degreees if number is between 0.25 and 0.5
				transform.Rotate(0f, -90f, 0f);
				
			} else if (rand > 0.98f && rand < 1.0f) {

				//1% chance that new pathmakerSpherePrefab is created at current position
				Instantiate(pathmakerSpherePrefab, transform.position, Quaternion.identity);

			}

			//creates new tile at current position
			Instantiate (floorPrefab, transform.position, Quaternion.identity);

			//moves 5 units based on its rotation
			transform.Translate (Vector3.forward * 5f); 

			counter++; //increments counter
			globalTileCount++; //increments number of tiles in world

			if (globalTileCount == maxTiles) { 
				//checks to see if there are maxTiles made, then destroys pathmaker
				Destroy (gameObject);
			}

		} else {
			Destroy (gameObject);
		}

		if (Input.GetKeyDown(KeyCode.R)) {
			//reloads scene where you press R
			SceneManager.LoadScene (SceneManager.GetActiveScene ().buildIndex); 

		}
	}
}
